---
title: "Comparison_Th1 and Th2"
output: html_document
---

```{r}
filelist= list.files(pattern = ".fpkm_tracking")
datalist = lapply(filelist, function(x)read.delim(x, header = T, as.is = T, stringsAsFactors = F))
datafr = do.call("cbind",datalist)
data_set <- datafr[,grep("FPKM", colnames(datafr))]
data_set <- data_set[,c(1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61,65,69,73,77)]
colnames (data_set) <- filelist
data_set$gene_id <- datafr[,4]
data_set[,1:21] <- data_set[,c(21,1:20)]
colnames (data_set) <- c("gene_id",filelist)
Th1<- data_set[grep("Th1",colnames(data_set))]
Th17 <- Th1[,-c(1,2,5,6)]
Th1 <- Th1[,c(1,2,5,6)]
Th2 <- data_set[grep("Th2",colnames(data_set))]
Th9 <- data_set[grep("Th9",colnames(data_set))]
Treg <- data_set[grep("Treg",colnames(data_set))]

data_set <- cbind(Th1, Th2, Th9, Th17, Treg)
length_gene <- nrow(data_set)
group <- factor(c(rep("Th1",4),rep("Th2",4),rep("Th9",4),rep("Th17",4),rep("Treg",4)))
expression_level <- as.data.frame(log2(1+data_set))
qqnorm(expression_level[,3])
qqline(expression_level[,3])
colnames(expression_level) <- c("Th1_1A","Th1_1B","Th1_2A","Th1_2B","Th2_1A","Th2_1B","Th2_2A","Th2_2B",
                                "Th9_1A","Th9_1B","Th9_2A","Th9_2B","Th17_1A","Th17_1B","Th17_2A","Th17_2B",
                                "Treg_1A","Treg_1B","Treg_2A","Treg_2B")
res <- cor(expression_level)
correlation_result <- round(res, 4)
library(corrplot)
plot_cor <-corrplot(correlation_result, method="circle")
#dev.off()
plot_cor
###PCA test for the data ## with Treg
PCA_data <- as.data.frame(t(expression_level))
PCA_data$group <- c(rep("Th1",4),rep("Th2",4),rep("Th9",4),rep("Th17",4),rep("Treg",4))
PCA_data$time <- c("Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2")
PCA_plot <- prcomp(PCA_data[,1:23847],center = TRUE, scale. = FALSE)
library(ggplot2)
ggplot(data=NULL, aes(PCA_plot$x[,1],PCA_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+xlab("First component") + ylab("Second component")+labs(color="celltype",shape="time")
PoV <- PCA_plot$sdev^2/sum(PCA_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)")
###PCA with Treg, genes with top 500 highest variance
variance_PCA <- apply(PCA_data[,1:23847],2,var)
variance_PCA <- order(variance_PCA,decreasing = T)
variance_PCA <- variance_PCA[1:500]
PCA_vari <- PCA_data[,variance_PCA]
PCA_var_plot <- prcomp(PCA_vari,center = T,scale. = F)
ggplot(data = NULL,aes(PCA_var_plot$x[,1],PCA_var_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+ xlab("First component") + ylab("Second component") + labs(color="celltype",shape="time")
PoV <- PCA_var_plot$sdev^2/sum(PCA_var_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)")
###Data without Treg, since they are much too different from the other Th cells)
PCA_data <- as.data.frame(t(expression_level))
PCA_data$group <- c(rep("Th1",4),rep("Th2",4),rep("Th9",4),rep("Th17",4),rep("Treg",4))
PCA_data$time <- c("Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2")
PCA_data <- PCA_data[1:16,]
PCA_plot <- prcomp(PCA_data[,1:23847],center = TRUE, scale. = FALSE)
library(ggplot2)
ggplot(data=NULL, aes(PCA_plot$x[,1],PCA_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+xlab("First component") + ylab("Second component")+labs(color="celltype",shape="time")
PoV <- PCA_plot$sdev^2/sum(PCA_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)")
### Treg no more considered, top 500 genes with the highest variance
variance_PCA <- apply(PCA_data[,1:23847],2,var)
variance_PCA <- order(variance_PCA,decreasing = T)
variance_PCA <- variance_PCA[1:500]
PCA_vari <- PCA_data[,variance_PCA]
PCA_var_plot <- prcomp(PCA_vari,center = T,scale. = F)
ggplot(data = NULL,aes(PCA_var_plot$x[,1],PCA_var_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+ xlab("First component") + ylab("Second component") + labs(color="celltype",shape="time")
PoV <- PCA_var_plot$sdev^2/sum(PCA_var_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)")
### If further leaving Th17
PCA_data <- as.data.frame(t(expression_level))
PCA_data$group <- c(rep("Th1",4),rep("Th2",4),rep("Th9",4),rep("Th17",4),rep("Treg",4))
PCA_data$time <- c("Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2")
PCA_data <- PCA_data[1:12,]
PCA_plot <- prcomp(PCA_data[,1:23847],center = TRUE, scale. = FALSE)
library(ggplot2)
ggplot(data=NULL, aes(PCA_plot$x[,1],PCA_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+xlab("First component") + ylab("Second component")+labs(color="celltype",shape="time")
PoV <- PCA_plot$sdev^2/sum(PCA_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)")
### No Th17 , top 500 genes with the highest variance
variance_PCA <- apply(PCA_data[,1:23847],2,var)
variance_PCA <- order(variance_PCA,decreasing = T)
variance_PCA <- variance_PCA[1:500]
PCA_vari <- PCA_data[,variance_PCA]
PCA_var_plot <- prcomp(PCA_vari,center = T,scale. = F)
ggplot(data = NULL,aes(PCA_var_plot$x[,1],PCA_var_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+ xlab("First component") + ylab("Second component") + labs(color="celltype",shape="time")
PoV <- PCA_var_plot$sdev^2/sum(PCA_var_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)") 
```
#Performing Differential Expression with Th1, Th2, Th9, Th17, Treg
```{r}
library(limma)

design <- model.matrix(~ 0 + factor(c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5)))
colnames(design) <- c( "Th1","Th2","Th9","Th17","Treg")
fit <- lmFit(expression_level,design =design)
contrast_mat <-makeContrasts(Th2-Th1,Th9-Th1,Th17-Th1,Treg-Th1,levels = design)
fit2 <- contrasts.fit(fit, contrast_mat)
fit <-eBayes(fit2, 0.01,trend = T)
p.adj<-p.adjust(fit$p.value,method = "fdr")
p.adj<-matrix(as.numeric(p.adj),ncol=4,nrow=23847)

Th1_sig<-as.data.frame(cbind(as.character(datafr$tracking_id),fit$p.value,p.adj))
names(Th1_sig)<-c("Gene_symbol","pvalue_Th2","pvalue_Th9","pvalue_Th17","pvalue_Treg",
                  "padj_Th2","padj_Th9","padj_Th17","padj_Treg")
#Th1_sig <- Th1_sig[(as.numeric(as.character(Th1_sig$padj_Th2)) <0.05 & as.numeric(as.character(Th1_sig$padj_Th9)) <0.05 &as.numeric(as.character(Th1_sig$padj_Th17)) <0.05 &
                     #as.numeric(as.character(Th1_sig$padj_Treg)) <0.05) , ]

Th1_sig <- Th1_sig[(as.numeric(as.character(Th1_sig$padj_Th2)) <0.05 & as.numeric(as.character(Th1_sig$padj_Th9)) <0.05 &as.numeric(as.character(Th1_sig$padj_Th17)) <0.05 ) , ]

library(limma)

design <- model.matrix(~ 0 + factor(c(1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2)))
colnames(design) <- c( "Th1","non_Th1" )
fit <- lmFit(expression_level,design =design)
contrast_mat <-makeContrasts(non_Th1-Th1,levels = design)
fit2 <- contrasts.fit(fit, contrast_mat)
fit <-eBayes(fit2, 0.01,trend = T)
p.adj<-p.adjust(fit$p.value,method = "fdr")
p.adj<-matrix(as.numeric(p.adj))

Th1_sig<-as.data.frame(cbind(as.character(datafr$tracking_id),fit$p.value,p.adj))
names(Th1_sig)<-c("Gene_symbol","pvalue_non_Th1","padj_non_Th1")
#Th1_sig <- Th1_sig[(as.numeric(as.character(Th1_sig$padj_Th2)) <0.05 & as.numeric(as.character(Th1_sig$padj_Th9)) <0.05 &as.numeric(as.character(Th1_sig$padj_Th17)) <0.05 &
#as.numeric(as.character(Th1_sig$padj_Treg)) <0.05) , ]

Th1_sig <- Th1_sig[as.numeric(as.character(Th1_sig$padj_non_Th1)) <0.05,]
nrow(Th1_sig)
#################################
```


```{r}
design <- model.matrix(~ 0 + factor(c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5)))
colnames(design) <- c( "Th1","Th2","Th9","Th17","Treg")
fit <- lmFit(expression_level,design =design)
contrast_mat <-makeContrasts(Th1-Th2,Th9-Th2,Th17-Th2,Treg-Th2,levels = design)
fit2 <- contrasts.fit(fit, contrast_mat)
fit <-eBayes(fit2, 0.01,trend = T)
p.adj<-p.adjust(fit$p.value,method = "fdr")
p.adj<-matrix(as.numeric(p.adj),ncol=4,nrow=23847)

Th2_sig<-as.data.frame(cbind(as.character(datafr$tracking_id),fit$p.value,p.adj))
names(Th2_sig)<-c("Gene_symbol","pvalue_Th1","pvalue_Th9","pvalue_Th17","pvalue_Treg",
                  "padj_Th1","padj_Th9","padj_Th17","padj_Treg")
#Th1_sig <- Th1_sig[(as.numeric(as.character(Th1_sig$padj_Th2)) <0.05 & as.numeric(as.character(Th1_sig$padj_Th9)) <0.05 &as.numeric(as.character(Th1_sig$padj_Th17)) <0.05 &
#as.numeric(as.character(Th1_sig$padj_Treg)) <0.05) , ]

Th2_sig <- Th2_sig[(as.numeric(as.character(Th2_sig$padj_Th1)) <0.05 & as.numeric(as.character(Th2_sig$padj_Th9)) <0.05 &as.numeric(as.character(Th2_sig$padj_Th17)) <0.05 ) , ]
nrow(Th2_sig)
```


```{r}
###########################apply this comparison to the Th2 type##############
library(limma)

design <- model.matrix(~ 0 + factor(c(2,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2)))
colnames(design) <- c( "Th2","non_Th2" )
fit <- lmFit(expression_level,design =design)
contrast_mat <-makeContrasts(non_Th2-Th2,levels = design)
fit2 <- contrasts.fit(fit, contrast_mat)
fit <-eBayes(fit2, 0.01,trend = T)
p.adj<-p.adjust(fit$p.value,method = "fdr")
p.adj<-matrix(as.numeric(p.adj))

Th2_sig<-as.data.frame(cbind(as.character(datafr$tracking_id),fit$p.value,p.adj))
names(Th2_sig)<-c("Gene_symbol","pvalue_non_Th2","padj_non_Th2")
#Th1_sig <- Th1_sig[(as.numeric(as.character(Th1_sig$padj_Th2)) <0.05 & as.numeric(as.character(Th1_sig$padj_Th9)) <0.05 &as.numeric(as.character(Th1_sig$padj_Th17)) <0.05 &
#as.numeric(as.character(Th1_sig$padj_Treg)) <0.05) , ]

Th2_sig <- Th2_sig[as.numeric(as.character(Th2_sig$padj_non_Th2)) <0.05,]
Th2_sig

```


```{r}
##########Treg as a trial################
library(limma)

design <- model.matrix(~ 0 + factor(c(2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1)))
colnames(design) <- c( "Treg","non_Treg" )
fit <- lmFit(expression_level,design =design)
contrast_mat <-makeContrasts(non_Treg-Treg,levels = design)
fit2 <- contrasts.fit(fit, contrast_mat)
fit <-eBayes(fit2, 0.01,trend = T)
p.adj<-p.adjust(fit$p.value,method = "fdr")
p.adj<-matrix(as.numeric(p.adj))

Treg_sig<-as.data.frame(cbind(as.character(datafr$tracking_id),fit$p.value,p.adj))
names(Treg_sig)<-c("Gene_symbol","pvalue_non_Treg","padj_non_Treg")
#Th1_sig <- Th1_sig[(as.numeric(as.character(Th1_sig$padj_Th2)) <0.05 & as.numeric(as.character(Th1_sig$padj_Th9)) <0.05 &as.numeric(as.character(Th1_sig$padj_Th17)) <0.05 &
#as.numeric(as.character(Th1_sig$padj_Treg)) <0.05) , ]

Treg_sig <- Treg_sig[as.numeric(as.character(Treg_sig$padj_non_Treg)) <0.05,]
```

# PCA analysis between Th1 and Th2
```{r}
PCA_data <- as.data.frame(t(expression_level))
PCA_data$group <- c(rep("Th1",4),rep("Th2",4),rep("Th9",4),rep("Th17",4),rep("Treg",4))
PCA_data$time <- c("Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2","Day_1","Day_1","Day_2","Day_2")
PCA_data <- PCA_data[1:8,]
PCA_plot <- prcomp(PCA_data[,1:23847],center = TRUE, scale. = FALSE)
library(ggplot2)
ggplot(data=NULL, aes(PCA_plot$x[,1],PCA_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+xlab("First component") + ylab("Second component")+labs(color="celltype",shape="time")
PoV <- PCA_plot$sdev^2/sum(PCA_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)")
### No Th17 , top 500 genes with the highest variance
variance_PCA <- apply(PCA_data[,1:23847],2,var)
variance_PCA <- order(variance_PCA,decreasing = T)
variance_PCA <- variance_PCA[1:500]
PCA_vari <- PCA_data[,variance_PCA]
PCA_var_plot <- prcomp(PCA_vari,center = T,scale. = F)
ggplot(data = NULL,aes(PCA_var_plot$x[,1],PCA_var_plot$x[,2],color=PCA_data$group,shape=PCA_data$time))+ geom_point()+ xlab("First component") + ylab("Second component") + labs(color="celltype",shape="time")
PoV <- PCA_var_plot$sdev^2/sum(PCA_var_plot$sdev^2)*100
barplot(PoV, xlab= "Dimensions", ylab="Proportion of explained variance (%)") 
```

# !However, since the different T helper cell subtypes are not similar to each other, that would be skeptical whether to regard them as a group.
# expressed eliminated the genes with extreme low expression levels
```{r}
# A good trial in this would be only to select the Th1 and Th2, and to compare them with each other for DE genes.
library(limma)

expressed <- apply(expression_level[,1:8],1,mean) > log2(1.2)

design <- model.matrix(~ 0 + factor(c(1,1,1,1,2,2,2,2)))
colnames(design) <- c( "Th1","Th2" )
fit <- lmFit(expression_level[expressed,1:8],design =design)
contrast_mat <-makeContrasts(Th2-Th1,levels = design)
fit2 <- contrasts.fit(fit, contrast_mat)
fit <-eBayes(fit2, 0.01,trend = T)
p.adj<-p.adjust(fit$p.value,method = "fdr")
p.adj<-matrix(as.numeric(p.adj))
Th1_exp <-expression_level[expressed,1:4]
Th1_exp$expression <- rowMeans(Th1_exp)
Th2_exp <- expression_level[expressed,5:8]
Th2_exp$expression <- rowMeans(Th2_exp)
#total_list <- data.frame(gene=datafr$tracking_id[expressed],
#                         log2FC=Th1_exp$expression-Th2_exp$expression )
library(qvalue)
results <- data.frame(gene=datafr$tracking_id[expressed],
                      log2FC=Th1_exp$expression
                                -Th2_exp$expression,
                      p.val=fit$p.value[,1],
                      p.adj=p.adjust(fit$p.value[,1],method = "fdr"),
                      q.val=qvalue(fit$p.value[,1])$qvalues
                      )
results$direction <- results$log2FC > 0

write.table(results, file = "~/R/Project_3_Lung Fibrosis/comparison_with_TH1_TH2/GSE99167_Comparison_for_TH/Comparison between different Th subtypes/All_genes_comparison_Th1_Th2_without_TP.txt", quote = F, row.names = FALSE)


#Draw the volcanic plot 
ggplot(mapping=aes(results$log2FC,-log10(results$p.adj)))+geom_point(size= 0.002,alpha=0.5)+ labs(x="log 2 fold change", y="-log10 adjusted p-value", title="Volcano Plot for Th1/Th2") + geom_hline(yintercept = -log10(0.05),color="red")

results.model1 <- results

Th1_2 <- results[results$p.adj <0.05,]

write.table(Th1_2, file = "~/R/Project_3_Lung Fibrosis/comparison_with_TH1_TH2/GSE99167_Comparison_for_TH/Comparison between different Th subtypes/Diff_genes_Th1_Th2_without_TP.txt", quote = F, row.names = FALSE)

### The result showed that the volcano plot for the differential expressed genes are not as expected... A reasonable explaination to this would be the influence of the time
```

# Include time point in the model

```{r}
# A good trial in this would be only to select the Th1 and Th2, and to compare them with each other for DE genes.
library(limma)

expressed <- apply(expression_level[,1:8],1,mean) > log2(1.2)

design <- model.matrix(~ 0 + factor(c(1,1,1,1,2,2,2,2))+
                    factor(c("T1","T1","T2","T2","T1","T1","T2","T2")))
colnames(design) <- c( "Th1","Th2","TP2" )
fit <- lmFit(expression_level[expressed,1:8],design =design)
contrast_mat <-makeContrasts(Th2-Th1,levels = design)
fit2 <- contrasts.fit(fit, contrast_mat)
fit <-eBayes(fit2, 0.01,trend = T)
p.adj<-p.adjust(fit$p.value,method = "fdr")
p.adj<-matrix(as.numeric(p.adj))
Th1_exp <-expression_level[expressed,1:4]
Th1_exp$expression <- rowMeans(Th1_exp)
Th2_exp <- expression_level[expressed,5:8]
Th2_exp$expression <- rowMeans(Th2_exp)
#total_list <- data.frame(gene=datafr$tracking_id[expressed],
#                         log2FC=Th1_exp$expression-Th2_exp$expression )
library(qvalue)
results <- data.frame(gene=datafr$tracking_id[expressed],
                      log2FC=Th1_exp$expression
                                -Th2_exp$expression,
                      p.val=fit$p.value[,1],
                      p.adj=p.adjust(fit$p.value[,1],method = "fdr"),
                      q.val=qvalue(fit$p.value[,1])$qvalues
                      )
results$direction <- results$log2FC > 0

write.table(results, file = "~/R/Project_3_Lung Fibrosis/comparison_with_TH1_TH2/GSE99167_Comparison_for_TH/Comparison between different Th subtypes/All_genes_comparison_Th1_Th2_includingTP.txt", quote = F, row.names = FALSE)
results.model2 <- results

#Draw the volcanic plot 
ggplot(mapping=aes(results$log2FC,-log10(results$p.adj)))+geom_point(size= 0.002,alpha=0.5)+ labs(x="log 2 fold change", y="-log10 adjusted p-value", title="Volcano Plot for Th1/Th2") + geom_hline(yintercept = -log10(0.05),color="red")

cat("Number of sig genes",sum(results$p.adj<0.05))
#names(Th1_2)<-c("Gene_symbol","pvalue_Th1_2","padj_Th1_2")

Th1_2 <- results[results$p.adj <0.05,]

write.table(Th1_2, file = "~/R/Project_3_Lung Fibrosis/comparison_with_TH1_TH2/GSE99167_Comparison_for_TH/Comparison between different Th subtypes/Diff_genes_Th1_Th2_including_TP.txt", quote = F, row.names = FALSE)

### The result showed that the volcano plot for the differential expressed genes are not as expected... A reasonable explaination to this would be the influence of the time

ggplot(mapping=aes(-log10(results.model1$p.val),-log10(results.model2$p.val)))+geom_point(size=0.003,alpha=0.1)+xlab("-log10(p_value generated without considering the influence of time)") + ylab("-log10(p_value generated with considering the influence of time)") + theme(axis.title.x = element_text(size = 6.5, colour = 'black'),axis.title.y = element_text(size = 6.5, colour = 'black', angle = 90))

```


