#!/bin/sh

# This is a shell script for the visualization process
# Input - a result generated by panther platform

# The first step is to split up the names and the GO numbers using R
echo "Please add a Panther result to the folder"
read -p "Is it an overrepresentation or enrichment result? Enter overrepresentation or enrichment " panther_method
echo $panther_method
if [ "$panther_method" = "overrepresentation" ] 
then 
	R< GO_trimmed_separation_overrepresentation.R --no-save
	chmod u+x GOAnnotations_overrepresentation.py
	python3 < GOAnnotations_overrepresentation.py
elif [ "$panther_method" = "enrichment" ] 
then 
	R< GO_trimmed_separation_enrichment.R --no-save
	chmod u+x GOAnnotations_enrichment.py
	python3 < GOAnnotations_enrichment.py
else 
echo "Please enter the right option"
fi

wait

# The result was to be sent to python for visualization

chmod u+x visualization_automated.py
python3 < visualization_automated.py
wait

R< Remove_duplicated_pathway.R --no-save
wait
R< extract_all_nodes.R --no-save
wait
chmod u+x GOterm_library.py
python3 < GOterm_library.py
wait
R< generating_table_in_JSON.R --no-save
wait

# Remove all the unwanted documents from the folder
rm "result/all_nodes_in the pathway.txt"
rm "result/BP_related_GOterms.txt"
rm "result/GO_best_pathway_for_cytoscape.sif"
rm "result/GO_number_for_visualization.txt"
rm "result/GO_numbers_involved_in_best_pathway.txt"
rm "result/GO_pathway.txt"
rm "result/parent_child.txt"

